version: '3.8'

services:
  app:
    build: .
    container_name: autoassist-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: production
      PORT: 8000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - autoassist-network

networks:
  autoassist-network:
    driver: bridge