# Docker Compose for AutoAssist Backend with MongoDB Atlas
# Use this configuration when using MongoDB Atlas (cloud)
version: "3.8"

services:
  # Backend API Service
  autoassist-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # MongoDB Atlas connection (required)
      - DATABASE_URL=${DATABASE_URL}
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      # JWT Configuration
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME}
      # CORS Configuration
      - FRONTEND_URL=${FRONTEND_URL}
      # Rate Limiting
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
    volumes:
      - ./data:/app/data
    networks:
      - autoassist-network
    restart: unless-stopped

networks:
  autoassist-network:
    driver: bridge
